- name: Install prerequisities
  include: prereqs.yml

- name: Configure the installer
  include: config.yml

- name: Run some checks before the installation
  include: check.yml

- name: Run the installation
  include: run.yml

- name: Wait for the bootstrap to complete
  include: wait.yml
