- block:
    - name: Log in to '{{ ovirt.ovirt_url }}'
      ovirt_auth:
        url: '{{ ovirt.ovirt_url }}'
        username: '{{ ovirt.ovirt_username }}'
        password: '{{ ovirt.ovirt_password }}'
        insecure: '{{ not ovirt.validate_certs }}'

    - name: Retrieve all machines in the cluster {{ ovirt.cluster_name }}
      ovirt_vm_info:
        auth: '{{ ovirt_auth }}'
        pattern: 'cluster="{{ ovirt.cluster_name }}"'
      register: ovirt_vms

    - name: Define existing virtual machines
      set_fact:
        ovirt_existing_vms: '{{ ovirt_vms.ovirt_vms | json_query("[*].name") }}'

    - name: Create virtual machines that don't exist
      include_tasks: deploy_host.yml
      when: virtual_machine_names[item.hostname] not in ovirt_existing_vms
      with_items: '{{ openshift_cluster_hosts }}'

  always:
    - name: Always revoke the SSO token, log out from '{{ ovirt.ovirt_url }}'
      ovirt_auth:
        state: absent
        ovirt_auth: '{{ ovirt_auth }}'
