- name: Generate ignition configs
  import_role:
    name: openshift_common
    tasks_from: generate_ignition.yml

- name: Ensure prerequisites
  import_tasks: ensure_prereqs.yml

- name: Deploy hosts
  import_tasks: deploy_hosts.yml

- name: Wait for the bootstrap to complete
  import_role:
    name: openshift_common
    tasks_from: wait_for_bootstrap.yml